name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  test-solr-9:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Setup solr
        run: |
          make solr-9
          make solrcloud-9

      - name: Run tests
        run: go test -tags integration -coverprofile=profile.cov

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          
  test-solr-8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Setup solr
        run: |
          make solr-8
          make solrcloud-8

      - name: Run tests
        run: go test -tags integration -coverprofile=profile.cov